allowBuilds:
  unrs-resolver: true

ignoredBuiltDependencies:
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.61.1'
  - '@typescript-eslint/parser@8.61.1'
  - '@typescript-eslint/project-service@8.61.1'
  - '@typescript-eslint/scope-manager@8.61.1'
  - '@typescript-eslint/tsconfig-utils@8.61.1'
  - '@typescript-eslint/type-utils@8.61.1'
  - '@typescript-eslint/types@8.61.1'
  - '@typescript-eslint/typescript-estree@8.61.1'
  - '@typescript-eslint/utils@8.61.1'
  - '@typescript-eslint/visitor-keys@8.61.1'
  - aws-cdk@2.1127.0
  - typescript-eslint@8.61.1
  - js-yaml@4.1.2

overrides:
  js-yaml@<=4.1.1: ^4.1.2
